version: "3.7"

volumes:
  librenms-mariadb-data:
  librenms-rrd-db:
  rrd-journal:
  librenms-data:


networks:
  librenms:
    driver: overlay
    attachable: false
    driver_opt: encrypted
    internal: true
  lan:
    external: true
    

services:
  reverse-proxy:
    image: traefik:alpine
    init: true
    deploy:
      mode: replicated
      replicas: '3'
      endpoint_mode: vip
      resources:
        limits:
          cpus: '2'
          memory: 2048m
        reservations:
          cpus: '0.5'
          memory: 512m
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: '3'
        window: 300s
      update-config:
        parallelism: '1'
        delay: 30s
        failure_action: rollback
        monitor: 15s
        order: stop-first
    command:
      - "--logLevel=INFO"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
#      - "--docker.domain=example.com"
#      - "--acme=true"
#      - "--acme.acmelogging=true"
#      - "--acme.email=webmaster@example.com"
#      - "--acme.storage=acme.json"
#      - "--acme.entryPoint=https"
#      - "--acme.onhostrule=true"
#      - "--acme.httpchallenge=true"
#      - "--acme.httpchallenge.entrypoint=http"
    ports:
      - target: "80"
        published: "192.168.1.3:80"
        protocol: tcp
        mode: ingress
      - target: "443"
        published: "192.168.1.3:443"
        protocol: tcp
        mode: ingress
    volumes:
#      - "./acme.json:/acme.json"
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/boot2docker/:/ssl:ro
    networks:
      - librenms
      - lan
#    restart: always

  db:
    image: mariadb:10.2
    init: true
    deploy:
      hostname: librenms_db
      mode: replicated
      replicas: '3'
      endpoint_mode: vip
      resources:
        limits:
          cpus: '3'
          memory: 8192m
        reservations:
          cpus: '1'
          memory: 2048m
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: '3'
        window: 300s
      update-config:
        parallelism: '1'
        delay: 30s
        failure_action: rollback
        monitor: 15s
        order: stop-first
    command: 
      - "mysqld"
      - "--sql-mode="
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - librenms-mariadb-data:/var/lib/mysql
    environment:
      - "TZ=${TZ:-America/Pacific}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-librenms}"
      - "MYSQL_USER=${MYSQL_USER:-librenms}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-librenms123secret}"
    networks:
      - librenms
      #    restart: always

  memcached:
    image: memcached:alpine
    init: true
    deploy:
      hostname: librenms_memcached
      mode: replicated
      replicas: '3'
      endpoint_mode: vip
      resources:
        limits:
          cpus: '1'
          memory: 8192m
        reservations:
          cpus: '0.5'
          memory: 8192m
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: '3'
        window: 300s
      update-config:
        parallelism: '1'
        delay: 30s
        failure_action: rollback
        monitor: 15s
        order: stop-first
    environment:
      - "TZ=${TZ:-America/Pacific}"
    networks:
      - librenms
#    restart: always

  rrdcached:
    image: crazymax/rrdcached
    init: true
    deploy:
      hostname: librenms_rrdcached
      mode: replicated
      replicas: '3'
      endpoint_mode: vip
      resources:
        limits:
          cpus: '4'
          memory: 2048m
        reservations:
          cpus: '0.5'
          memory: 512m
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: '3'
        window: 300s
      update-config:
        parallelism: '1'
        delay: 30s
        failure_action: rollback
        monitor: 15s
        order: stop-first
    volumes:
      - librenms-rrd-db:/data/db
      - rrd-journal:/data/journal
    environment:
      - "TZ=${TZ:-America/Pacific}"
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "LOG_LEVEL=LOG_INFO"
      - "WRITE_TIMEOUT=1800"
      - "WRITE_JITTER=1800"
      - "WRITE_THREADS=4"
      - "FLUSH_DEAD_DATA_INTERVAL=3600"
    networks:
      - librenms
    expose:
      - "42217"
#    restart: always

#  smtp:
#    image: juanluisbaptiste/postfix
#    init: true
#    container_name: librenms_smtp
#    deploy:
#      mode: replicated
#      replicas: '3'
#      endpoint_mode: vip
#      resources:
#        limits:
#          cpus: '1'
#          memory: 1024m
#        reservations:
#          cpus: '0.5'
#          memory: 512m
#      restart_policy:
#        condition: any
#        delay: 5s
#        max_attempts: '3'
#        window: 300s
#      update-config:
#        parallelism: '1'
#        delay: 30s
#        failure_action: rollback
#        monitor: 15s
#        order: stop-first
#    volumes:
#      - "/etc/localtime:/etc/localtime:ro"
#    environment:
#      - "SERVER_HOSTNAME=192.168.1.3"
#      - "SMTP_SERVER=${SMTP_SERVER}"
#      - "SMTP_USERNAME=${SMTP_USERNAME}"
#      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
#    networks:
#      - librenms
#      - nat
#    restart: always


  librenms:
    image: librenms/librenms:latest
    init: true
#    depends_on:
#      - db
#      - memcached
#      - rrdcached
#      - smtp
    deploy:
#      domainname: example.com
      hostname: librenms
      mode: replicated
      replicas: '3'
      endpoint_mode: vip
      resources:
        limits:
          cpus: '4'
          memory: 8192m
        reservations:
          cpus: '2'
          memory: 4096m
      restart_policy:
        condition: any
        delay: 25s
        max_attempts: '5'
        window: 300s
      update-config:
        parallelism: '1'
        delay: 30s
        failure_action: rollback
        monitor: 15s
        order: stop-first
    volumes:
      - librenms:/data
    labels:
      - "traefik.enable=true"
      - "traefik.backend=librenms"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:192.168.1.3"
    environment:
      - "TZ=${TZ:-America/Pacific}"
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE:-librenms}"
      - "DB_USER=${MYSQL_USER:-librenms}"
      - "DB_PASSWORD=${MYSQL_PASSWORD:-librenms123secret}"
      - "DB_TIMEOUT=30"
    env_file:
      - "./librenms.env"
#    restart: always

  cron:
    image: librenms/librenms:latest
    init: true
    container_name: librenms_cron
#    depends_on:
#      - librenms
    deploy:
#      domainname: example.com
      hostname: librenms-cron
      resources:
        limits:
          cpus: '12'
          memory: 8192m
        reservations:
          cpus: '0.5'
          memory: 512m
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: '3'
        window: 300s
      update-config:
        parallelism: '1'
        delay: 30s
        failure_action: rollback
        monitor: 15s
        order: stop-first
    volumes:
      - librenms-data:/data
    environment:
      - "TZ=${TZ:-America/Pacific}"
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE:-librenms}"
      - "DB_USER=${MYSQL_USER:-librenms}"
      - "DB_PASSWORD=${MYSQL_PASSWORD:-librenms123secret}"
      - "DB_TIMEOUT=30"
      - "SIDECAR_CRON=1"
    env_file:
      - "./librenms.env"
#    restart: always

  syslog-ng:
    image: librenms/librenms:latest
    init: true
#    depends_on:
#      - librenms
    deploy:
      hostname: librenms_syslog
      mode: replicated
      replicas: '3'
      endpoint_mode: vip
      resources:
        limits:
          cpus: '4'
          memory: 4096m
        reservations:
          cpus: '2'
          memory: 2048m
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: '3'
        window: 300s
      update-config:
        parallelism: '1'
        delay: 30s
        failure_action: rollback
        monitor: 15s
        order: stop-first
    ports:
      - target: "514"
        published: 192.168.1.3:514
        protocol: tcp
      - target: "514"
        published: 192.168.1.3:514
        protocol: udp
    volumes:
      - librenms-data:/data
    environment:
      - "TZ=${TZ:-America/Pacific}"
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE:-librenms}"
      - "DB_USER=${MYSQL_USER:-librenms}"
      - "DB_PASSWORD=${MYSQL_PASSWORD:-librenms123secret}"
      - "DB_TIMEOUT=30"
      - "SIDECAR_SYSLOGNG=1"
    env_file:
      - "./librenms.env"
#    restart: always
